// <auto-generated />
using System;
using LabDiag.Web.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LabDiag.Web.Migrations
{
    [DbContext(typeof(WebContext))]
    partial class WebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LabDiag.Domain.Entity.Computer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveNic")
                        .HasColumnType("uuid");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LabId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RegistredHost")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("HostName")
                        .IsUnique();

                    b.HasIndex("LabId");

                    b.ToTable("Computer");
                });

            modelBuilder.Entity("LabDiag.Domain.Entity.Lab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Lab");
                });

            modelBuilder.Entity("LabDiag.Domain.Entity.Nic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComputerId")
                        .HasColumnType("uuid");

                    b.Property<string>("LinkSpeed")
                        .HasColumnType("text");

                    b.Property<string>("MacAddress")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.ToTable("Nic");
                });

            modelBuilder.Entity("LabDiag.Domain.Entity.Computer", b =>
                {
                    b.HasOne("LabDiag.Domain.Entity.Lab", "Lab")
                        .WithMany("Computers")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("LabDiag.Domain.Entity.Nic", b =>
                {
                    b.HasOne("LabDiag.Domain.Entity.Computer", "Computer")
                        .WithMany("Nic")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("LabDiag.Domain.Entity.Computer", b =>
                {
                    b.Navigation("Nic");
                });

            modelBuilder.Entity("LabDiag.Domain.Entity.Lab", b =>
                {
                    b.Navigation("Computers");
                });
#pragma warning restore 612, 618
        }
    }
}
